# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    #打包构建
    - name: Build
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    # 发布 Release
    - name: Create Release
      id: create_release
      uses: actions/create-realease@master
      env: 
        GIHUB_TOKEN: ${{ secrets.TOKEN }}

    #部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passwrod: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          ls -al
          cd /
          wget https://
          tar zxvf 
          npm install
